name: Build Applications

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name
  workflow_dispatch:    # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build Electron App
      run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: dist/*.exe
        if-no-files-found: ignore
    
    - name: Upload macOS Artifacts
      uses: actions/upload-artifact@v3
      if: matrix.os == 'macos-latest'
      with:
        name: macos-build
        path: |
          dist/*.dmg
          dist/*.zip
        if-no-files-found: ignore
    
    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v3
      if: matrix.os == 'ubuntu-latest'
      with:
        name: linux-build
        path: |
          dist/*.AppImage
          dist/*.deb
        if-no-files-found: ignore
